name: Output Issues Event
on:
  issues:
    types:
      - opened

jobs:
  Output_Issue_Details:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Github Context
        run: echo "${{ toJSON(github) }}"